plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"
packageExtensions:
  "webpack-dev-server@*":
    peerDependenciesMeta:
      "webpack-cli":
        optional: true
  "fork-ts-checker-webpack-plugin@*":
    peerDependenciesMeta:
      "typescript":
        optional: true
  "babel-loader@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
